version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=mycmdb
      - POSTGRES_USER=mycmdb
      - POSTGRES_PASSWORD=mycmdb
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=mycmdb.settings.sqlite
    volumes:
      - .:/code
    ports:
      - "8000:8000/tcp"
    depends_on:
      - db