# Generated by Django 2.2.7 on 2019-11-28 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='hostname')),
                ('max_ports', models.PositiveSmallIntegerField(blank=True, default=4, verbose_name='max ports')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_number', models.PositiveSmallIntegerField(default=1, verbose_name='server number')),
                ('switch_number', models.PositiveSmallIntegerField(default=1, verbose_name='switch number')),
                ('server_port', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_ports', to='cmdb.Asset')),
                ('switch_port', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switch_ports', to='cmdb.Asset')),
            ],
            options={
                'unique_together': {('server_port', 'switch_port')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='ports',
            field=models.ManyToManyField(blank=True, default=None, related_name='portss', through='cmdb.Port', to='cmdb.Asset'),
        ),
    ]
