# Generated by Django 2.2.7 on 2019-11-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
    ]
