# Generated by Django 2.2.7 on 2019-11-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20191118_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ports',
            field=models.ManyToManyField(blank=True, default=None, related_name='portes', related_query_name='portess', through='cmdb.Port', to='cmdb.Asset'),
        ),
    ]
