# Generated by Django 2.2.7 on 2019-11-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20191118_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ports',
            field=models.ManyToManyField(blank=True, default=None, related_name='portss', through='cmdb.Port', to='cmdb.Asset'),
        ),
    ]
